### ISSUE TITLE
Issue running on python 3.10, MacOS 15.1. - Unable to import submodules

### ISSUE THREAD

**Issue by jakes44** [egagli/easysnowdata#12]
### Environment Information

-   easysnowdata version: 0.0.1
-   Python version: 3.10
-   Operating System: MacOS 15.1

### Description

Not able to import or use any sub-modules of easysnowdata

### What I Did
1. Installed easysnowdata via pip into my local virtual environment (by running `pixi add easysnowdata --pypi`)
2. In a jupyter notebook, ran the example code (or tried to) to get Snotel Data
3. Got error regarding module not found

```
import easysnowdata

StationCollection = easysnowdata.automatic_weather_stations.StationCollection()
```

```
AttributeError: module 'easysnowdata' has no attribute 'automatic_weather_stations'

```

**Comment by egagli** [comment]
Oh interesting! I notice it says easysnowdata version is 0.0.1, however the current version is 0.0.11, and I don't think the automatic_weather_stations module was around at that time. What happens when you try pip install easysnowdata?

**Comment by jakes44** [comment]
🤦 It was indeed just a versioning issue - pixi was resolving to less than `0.0.11` since some other dependency conflicts, but manually getting those sorted allowed me to use the correct version. 

Closing, thanks!
